-- MySQL Script generated by MySQL Workbench
-- Sun Oct 31 11:13:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb  FUNCIONA
-- -----------------------------------------------------
DROP DATABASE IF EXISTS dbviveros;

CREATE DATABASE dbviveros;
\c dbviveros

-- -----------------------------------------------------
-- Table VIVEROS    FUNCIONA
-- -----------------------------------------------------
DROP TABLE IF EXISTS VIVEROS;

CREATE TABLE IF NOT EXISTS VIVEROS (
          Coordenadas_Geograficas INT NOT NULL,
          Nombre VARCHAR(30) NOT NULL,
          Superficie VARCHAR(20) NOT NULL,
          PRIMARY KEY (Coordenadas_Geograficas),
          UNIQUE (Nombre));

-- -----------------------------------------------------
-- Table prueba.ZONAS   FUNCIONA
-- -----------------------------------------------------
DROP TABLE IF EXISTS ZONAS;

CREATE TABLE IF NOT EXISTS ZONAS (
          Coordenadas_Geograficas INT NOT NULL,
          Nombre VARCHAR(30) NOT NULL,
          PRIMARY KEY (Nombre),
          UNIQUE (Coordenadas_Geograficas),
          CONSTRAINT fk_ZONAS_VIVEROS
          FOREIGN KEY (Coordenadas_Geograficas) 
            REFERENCES VIVEROS (Coordenadas_Geograficas)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table prueba.EMPLEADOS
-- -----------------------------------------------------
DROP TABLE IF EXISTS EMPLEADOS;

CREATE TABLE IF NOT EXISTS EMPLEADOS (
          DNI INT NOT NULL,
          Nombre VARCHAR(45) NOT NULL,
          Sueldo FLOAT NOT NULL,
          Direccion VARCHAR(45) NOT NULL,
          PRIMARY KEY (DNI),
          UNIQUE (Nombre));



-- -----------------------------------------------------
-- Table prueba.CLIENTES_PLUS  FUNCIONA
-- -----------------------------------------------------
DROP TABLE IF EXISTS CLIENTES_PLUS;

CREATE TABLE IF NOT EXISTS CLIENTES_PLUS (
          DNI INT NOT NULL,
          Total_Mensual FLOAT NULL,
          Bonificacion FLOAT NULL,
          EMPLEADOS_DNI INT NOT NULL,
          PRIMARY KEY (DNI),
          CONSTRAINT fk_CLIENTES_PLUS_EMPLEADOS1
            FOREIGN KEY (EMPLEADOS_DNI)
            REFERENCES EMPLEADOS (DNI)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table prueba.PRODUCTOS
-- -----------------------------------------------------
DROP TABLE IF EXISTS PRODUCTOS;

CREATE TABLE IF NOT EXISTS PRODUCTOS (
          Codigo_Producto INT NOT NULL,
          Nombre VARCHAR(45) NOT NULL,
          Precio FLOAT NOT NULL,
          PRIMARY KEY (Codigo_Producto));


-- -----------------------------------------------------
-- Table prueba.CLIENTES PLUS_PRODUCTOS
-- -----------------------------------------------------
DROP TABLE IF EXISTS CLIENTES_PLUS_PRODUCTOS;

CREATE TABLE IF NOT EXISTS CLIENTES_PLUS_PRODUCTOS (
          CLIENTES_PLUS_DNI INT NOT NULL,
          PRODUCTOS_Codigo_Producto INT NOT NULL,
          Fecha DATE NOT NULL,
          PRIMARY KEY (CLIENTES_PLUS_DNI, PRODUCTOS_Codigo_Producto, Fecha),
          CONSTRAINT fk_CLIENTES_PLUS_has_PRODUCTOS_CLIENTES_PLUS1
            FOREIGN KEY (CLIENTES_PLUS_DNI)
            REFERENCES CLIENTES_PLUS (DNI)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
          CONSTRAINT fk_CLIENTES_PLUS_has_PRODUCTOS_PRODUCTOS1
            FOREIGN KEY (PRODUCTOS_Codigo_Producto)
            REFERENCES PRODUCTOS (Codigo_Producto)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table prueba.ZONAS_PRODUCTOS
-- -----------------------------------------------------
DROP TABLE IF EXISTS ZONAS_PRODUCTOS;

CREATE TABLE IF NOT EXISTS ZONAS_PRODUCTOS (
          Coordenadas_Geograficas INT NOT NULL,
          Nombre VARCHAR(45) NOT NULL,
          Codigo_Producto INT NOT NULL,
          Stock INT NULL,
          PRODUCTOS_Codigo_Producto INT NOT NULL,
          ZONAS_Coordenadas_Geograficas INT NOT NULL,
          PRIMARY KEY (Coordenadas_Geograficas),
          UNIQUE (Nombre),
          CONSTRAINT fk_ZONAS_PRODUCTOS_PRODUCTOS1
            FOREIGN KEY (PRODUCTOS_Codigo_Producto)
            REFERENCES PRODUCTOS (Codigo_Producto)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
          CONSTRAINT fk_ZONAS_PRODUCTOS_ZONAS1
            FOREIGN KEY (ZONAS_Coordenadas_Geograficas)
            REFERENCES ZONAS (Coordenadas_Geograficas)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION);


-- ----------------------------------------------------